name: TALC updater

on:
  schedule:
    # Runs at 11:00 on the first of every month
    - cron: '0 11 1 * *'
  workflow_dispatch:

jobs:
  talc_update:
    runs-on: ubuntu-latest
    # This condition checks if the current repository is NOT the base repository
    if: ${{ github.repository != 'roald/talc' }}
    steps:
      # Step 1: Check out the current repository
      - name: Check out the current repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      # Step 2: Configure user for Git
      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      # Step 3: Create a new branch for the changes
      - name: Create a new branch
        run: |
          git checkout -b talc-update

      # Step 4: Pull changes from the base repository
      - name: Pull changes from the base repository
        env:
          TALC_ACCESS_TOKEN: ${{ secrets.TALC_ACCESS_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git remote add talc https://${{ env.TALC_ACCESS_TOKEN }}:x-oauth-basic@github.com/roald/talc.git
          git fetch talc main
          git merge talc/main

      # Step 5: Push the branch to the remote
      - name: Push the branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: talc-update

      # Step 6: Create a pull request
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_branch: "main"
          source_branch: "talc-update"
          pr_title: "TALC update from base repository"
          pr_body: |
            # TALC update!
            This is an automated Pull Request with updates from the TALC base repository.
          pr_reviewer: "roald"
          pr_label: "talc"
